import { Quicksand } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar.jsx";
import Footer from "../components/Footer.jsx";
import { ToastContainer } from "react-toastify";

const QuicksandFont = Quicksand({
  subsets: ["latin"],
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme="Light"
      className={`${QuicksandFont.className} h-full antialiased`}
    >
      <body className="bg-[#EFE4D2]">
        <Navbar />
         <main className="w-[90%] md:container mx-auto">
          {children}
         </main>
         <ToastContainer />
        <Footer />
      </body>
    </html>
  );
}
